# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for InfluxDB MCP Server
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --production

# Copy source code
COPY src ./src

# Use lightweight non-root user (optional)
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

# Entrypoint for MCP server (using stdio transport)
ENTRYPOINT ["node", "src/index.js"]
